version: '2'
services:
  namesrv:
    image: coll/rocketmq-namesrv:4.2.0
    container_name: namesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/opt/logs
      - ./data/namesrv/store:/opt/store
  broker-node_a:
    image: coll/rocketmq-broker:4.2.0
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./data/broker-node_a/logs:/opt/logs
      - ./data/broker-node_a/store:/opt/store
    depends_on:
      - namesrv
  broker-node_b:
    image: coll/rocketmq-broker:4.2.0
    ports:
      - 10908:10908
      - 10910:10910
    volumes:
      - ./data/broker-node_b/logs:/opt/logs
      - ./data/broker-node_b/store:/opt/store
    depends_on:
      - namesrv
